# valid store type options { 1 = http SPARQLRepository, 2 = NativeStore, 3 = inMemoryStore}
store:
    type: 3
    url: http://136.243.4.200:8892/repositories/test
    username: test
    password: tester
    dir: /tmp/fdp-store/
urlPath:
    root: /fdp
metadataProperties:
    rootSpecs: http://rdf.biosemantics.org/fdp/shex/fdpMetadata
    catalogSpecs: http://rdf.biosemantics.org/fdp/shex/catalogMetadata
    datasetSpecs: http://rdf.biosemantics.org/fdp/shex/datasetMetadata
    distributionSpecs: http://rdf.biosemantics.org/fdp/shex/distributionMetadata   
    publisherURI: http://dtls.nl
    publisherName: dtls
    language: http://id.loc.gov/vocabulary/iso639-1/en
    license: http://rdflicense.appspot.com/rdflicense/cc-by-nc-nd3.0
fairSearch:
    fdpSubmitUrl: http://localhost:8080/fse/submitFdp
threadPoolSize: 4
metadataFM:
    F1:
        A: http://example.com/THIS_IS_A_PH_URI_4_ID_SCHEME
        B: http://example.com/THIS_IS_A_PH_URI_4_ID_PERSISTENCE
    A1:
        1: http://example.com/THIS_IS_A_PH_URI_4_ACCESS_PROTOCOL
    A2: http://example.com/THIS_IS_A_PH_URI_4_MD_LONGEVITY
